export const GET_MASCOTAS = "GET_MASCOTAS";
export const GET_USERS = "GET_USERS";
export const CREATE_USER = "CREATE_USER";
export const CREATE_ANIMAL = "CREATE_ANIMAL";
export const GET_ANIMAL_BY_ID = "GET_ANIMAL_BY_ID";
export const GET_GATO = "GET_GATO";
export const GET_PERRO = "GET_PERRO";
export const PAGO_MERCADO_PAGO = "PAGO_MERCADO_PAGO";
export const ORDEN_PERRO = "ORDEN_PERRO";
export const ORDEN_GATO = "ORDEN_GATO";
export const GET_DOG_LOCALIDAD = "GET_DOG_LOCALIDAD";
export const RESET_DOG = "RESET_DOG";
export const FILTRA_TAMAÑO = "FILTRA_TAMAÑO";
export const GET_CAT_LOCALIDAD = "GET_CAT_LOCALIDAD";
export const GET_DOG_TAMAÑOS = "GET_DOG_TAMAÑOS";
export const GET_TAMAÑO_PERDIDOS = "GET_TAMAÑO_PERDIDOS";
export const GET_ANIMALES_PERDIDOS = "GET_ANIMALES_PERDIDOS";
export const GET_TAMAÑO_FILTRO = "GET_TAMAÑO_FILTRO";
export const GET_DETAIL_MASCOTA_PERDIDA = "GET_DETAIL_MASCOTA_PERDIDA";
export const FILTRADO_ESTADO_PERDIDO = "FILTRADO_ESTADO_PERDIDO";
export const GET_GATO_PERDIDO = "GET_GATO_PERDIDO";
export const GET_PERRO_PERDIDO = "GET_PERRO_PERDIDO";
export const CREATE_ANIMAL_PERDIDO = "CREATE_ANIMAL_PERDIDO";
export const CREATE_LOCATION = "CREATE_LOCATION";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const PAGO_STRIPES = "PAGO_STRIPES";
export const CREATE_LOCATION_PERDIDOS = "CREATE_LOCATION_PERDIDOS";
export const GET_LOCATION_PERDIDOS = "GET_LOCATION_PERDIDOS";
export const GET_CAT_TAMAÑOS = "GET_CAT_TAMAÑOS";
export const GET_DOG_EDAD = "GET_DOG_EDAD";
export const GET_CAT_EDAD = "GET_CAT_EDAD";
export const CREATE_USER_GOOGLE = "CREATE_USER_GOOGLE";
export const CREATE_POST = "CREATE_POST";
export const GET_POSTS = "GET_POSTS";
export const GET_POST_ID = "GET_POST_ID";
export const CREATE_RESPUESTA = "CREATE_RESPUESTA";
export const GET_RESPUESTA = "GET_RESPUESTA";
export const CREATE_LIKE = "CREATE_LIKE";
export const GET_LIKES = "GET_LIKES";
export const MAIL_VERIFICAR_USUARIO = "MAIL_VERIFICAR_USUARIO";
export const EMAIL_INFO_ADOPTANTE = "EMAIL_INFO_ADOPTANTE";
export const CREATE_FAVORITO = "CREATE_FAVORITO";
export const GET_FAVORITOS = "GET_FAVORITOS";
export const CREAR_USUARIO_VALIDADO = "CREAR_USUARIO_VALIDADO";
export const POST_PAYPAL = "POST_PAYPAL";
export const GET_PAGOS = "GET_PAGOS";
export const DELETE_USER = "DELETE_USER";






